-- 创建评论表
CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL,
  avatar TEXT DEFAULT '',
  text TEXT NOT NULL,
  date TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 启用行级安全策略
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- 允许所有人读取评论
CREATE POLICY "Public comments are viewable by everyone."
  ON comments FOR SELECT
  USING (true);

-- 允许所有人插入评论
CREATE POLICY "Users can insert comments."
  ON comments FOR INSERT
  WITH CHECK (true);

-- 创建文章阅读量表
CREATE TABLE post_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_slug TEXT NOT NULL UNIQUE,
  view_count INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 创建索引提高查询性能
CREATE INDEX idx_post_views_slug ON post_views(post_slug);

-- 启用行级安全策略
ALTER TABLE post_views ENABLE ROW LEVEL SECURITY;

-- 允许所有人读取阅读量
CREATE POLICY "Post views are viewable by everyone."
  ON post_views FOR SELECT
  USING (true);

-- 允许所有人更新阅读量（通过存储过程）
CREATE POLICY "Post views can be updated by everyone."
  ON post_views FOR UPDATE
  USING (true);

-- 允许所有人插入新文章的阅读量记录
CREATE POLICY "New post views can be inserted."
  ON post_views FOR INSERT
  WITH CHECK (true);

-- 创建函数：增加阅读量
CREATE OR REPLACE FUNCTION increment_post_view(post_slug_param TEXT)
RETURNS VOID AS $$
BEGIN
  INSERT INTO post_views (post_slug, view_count)
  VALUES (post_slug_param, 1)
  ON CONFLICT (post_slug)
  DO UPDATE SET
    view_count = post_views.view_count + 1,
    updated_at = CURRENT_TIMESTAMP;
END;
$$ LANGUAGE plpgsql;